FROM nvidia/cuda:10.2-devel-ubuntu16.04

ARG user_uid

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo \
    cmake \
    wget \
    git \
    cuda-samples-10-2 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo 'deb [arch=amd64 trusted=yes] http://repo.radeon.com/rocm/apt/debian/ xenial main' | tee /etc/apt/sources.list.d/rocm.list

RUN apt-get update && \
    apt-get install -y hip-base hcc && \
    apt-get download hip-nvcc && \
    dpkg -i --ignore-depends=cuda hip*.deb \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
