# Parameters related to building hipcub
ARG base_image

FROM ${base_image}

LABEL maintainer="hipcub-maintainer@amd.com"

# Copy the debian package of hipcub into the container from host
COPY *.deb /tmp/

# Install the debian package, and print out contents of expected changed locations
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --allow-unauthenticated -y \
    /tmp/hipcub-*.deb \
  && rm -f /tmp/*.deb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && printf "ls -la /etc/ld.so.conf.d/\n" && ls -la /etc/ld.so.conf.d/ \
  && printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include \
  && printf "ls -la /opt/rocm/lib\n" && ls -la /opt/rocm/lib \
  && printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake \
  && printf "ls -la /opt/rocm/hipcub/include\n" && ls -la /opt/rocm/hipcub/include \
  && printf "ls -la /opt/rocm/hipcub/lib\n" && ls -la /opt/rocm/hipcub/lib
